CREATE TABLE [dbo].[Word]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Word] VARCHAR(30) NOT NULL, 
    [GameID] INT NOT NULL, 
    [Player] VARCHAR(36) NOT NULL, 
    [Score] INT NOT NULL, 
    CONSTRAINT [FK_Word_Games] FOREIGN KEY (GameID) REFERENCES Games(GameID), 
    CONSTRAINT [FK_Word_Users] FOREIGN KEY (Player) REFERENCES Users(UserID)
)
